# Generated by Django 4.2.16 on 2024-12-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.property'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.unit'),
        ),
        migrations.AlterField(
            model_name='expenserecorditem',
            name='expense_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.expenserecord'),
        ),
        migrations.AlterField(
            model_name='maintquote',
            name='maint_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.maintrecord'),
        ),
        migrations.AlterField(
            model_name='maintquoteinvoice',
            name='maint_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.maintquote'),
        ),
        migrations.AlterField(
            model_name='maintquoteitem',
            name='maint_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.maintquote'),
        ),
        migrations.AlterField(
            model_name='maintrecord',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.property'),
        ),
        migrations.AlterField(
            model_name='maintrecord',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.unit'),
        ),
        migrations.AlterField(
            model_name='maintrecorditem',
            name='maint_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.maintrecord'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.tenant'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.unit'),
        ),
        migrations.AlterField(
            model_name='rentalinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.tenant'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.property'),
        ),
    ]
