# Generated by Django 4.2.16 on 2024-11-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenserecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='expenserecorditem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'managed': False},
        ),
    ]
