# Generated by Django 4.2.16 on 2024-12-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_alter_expenserecord_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinvoice',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.rentalagreement'),
        ),
    ]
