# Generated by Django 5.1.1 on 2024-11-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('expense_record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expense_report_date', models.DateField()),
                ('expense_total', models.TextField()),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'expense_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecordItem',
            fields=[
                ('expense_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expense_item_name', models.TextField()),
                ('expense_item_cost', models.TextField(blank=True, null=True)),
                ('expense_type', models.TextField()),
                ('expense_category', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'expense_record_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintQuote',
            fields=[
                ('maint_quote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maint_quote_date', models.DateField()),
                ('quote_total', models.TextField()),
            ],
            options={
                'db_table': 'maint_quote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintQuoteInvoice',
            fields=[
                ('maint_invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('check_num', models.TextField(null=True)),
                ('amount_paid', models.TextField()),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'maint_quote_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintQuoteItem',
            fields=[
                ('quote_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quote_item_name', models.TextField()),
                ('quote_item_cost', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maint_quote_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintRecord',
            fields=[
                ('maint_record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maint_record_date', models.DateField()),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'maint_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintRecordItem',
            fields=[
                ('maint_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maint_item_name', models.TextField()),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'maint_record_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('street_addr', models.TextField()),
                ('city', models.TextField()),
                ('county', models.TextField(null=True)),
                ('state_abrv', models.TextField()),
                ('zip', models.TextField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('sqr_ft', models.TextField(blank=True, null=True)),
                ('price_per_sqqr_ft', models.TextField(blank=True, null=True)),
                ('purchase_price', models.TextField(blank=True, null=True)),
                ('market_price', models.TextField(blank=True, null=True)),
                ('num_of_units', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('agreement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_num', models.TextField(null=True)),
                ('contract_docs', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('curr_rent', models.TextField()),
                ('accepted', models.BooleanField()),
                ('active', models.BooleanField()),
                ('payment_sched', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('next_increase', models.DateField(blank=True, null=True)),
                ('last_increase', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rental_agreement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentalInvoice',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('cash_date', models.DateField(blank=True, null=True)),
                ('check_num', models.TextField(null=True)),
                ('amount_paid', models.TextField()),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'rental_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tenant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('unit_number', models.TextField()),
                ('sqr_ft', models.TextField(blank=True, null=True)),
                ('price_per_sqqr_ft', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'unit',
                'managed': False,
            },
        ),
    ]
